language: php

php:
  - 7.0
  - 7.1


sudo: false

cache:
  directories:
    - $HOME/.composer/cache


before_script:
  - travis_retry composer update -v --no-interaction --prefer-dist


script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover


