language: php

php:
  - 7.0
  - 7.1
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache


before_script:


script:
  - vendor/bin/phpcs --encoding=utf-8 --standard=PSR2  src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover


