language: php
sudo: required
dist: trusty
group: edge

php:
  - 7.0
  - 7.1
  - hhvm-nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: hhvm
      env: 'COMPOSER_FLAGS="--ignore-platform-reqs"'



before_script:
  - travis_retry composer update -v --no-interaction --prefer-dist ${COMPOSER_FLAGS}


script:
  - vendor/bin/phpcs --encoding=utf-8 --standard=PSR2  src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover


